baseURL = "https://Kaal-Misconfig.github.io/misconfig/"
languageCode = "en-us"
title = "M1$C0NF1G"
theme = "PaperMod"
pagerSize = 10

enableRobotsTXT = true

[Author]
  name = "Kaal"
  email = "your-email@example.com" # Highly recommended for better authorship signals
  homepage = "https://Kaal-Misconfig.github.io/misconfig/"

[params]
  env = "production"
  defaultTheme = "dark"
  disableThemeToggle = true
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  showtoc = true
  tocopen = false
  hideMeta = false
  author = "Kaal"
  ShowPostNavLinks = true

[params.homeInfoParams]
  Title = "ABOUT ME"
  Content = ""

[params.assets]
  css = ["css/extended/htb.css"]

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts"
    weight = 1

  [[menu.main]]
    name = "HTB"
    url = "HTB"
    weight = 4

  [[menu.main]]
    name = "THM"
    url = "THM"
    weight = 3

  [[menu.main]]
    name = "Notes"
    url = "notes"
    weight = 2

  [[menu.main]]
    name = "Tools"
    url = "/tools/"
    weight = 5

  [[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 6

  [[menu.main]]
    name = "Categories"
    url = "categories"
    weight = 7
